version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: workoutdb
      POSTGRES_USER: workoutuser
      POSTGRES_PASSWORD: workoutpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
